# Generated by Django 5.0.6 on 2025-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cupo', models.IntegerField(verbose_name='Cupo Máximo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('imagen', models.ImageField(upload_to='cursos/', verbose_name='Imagen del Curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Nuevo Curso',
                'verbose_name_plural': 'Nuevos Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
